export const exampleList = [
  { name: 'combobox', path: '/example/command/combobox' },
  { name: 'demo', path: '/example/command/demo' },
  { name: 'dialog', path: '/example/command/dialog' },
  {
    name: 'dropdown-menu',
    path: '/example/command/dropdown-menu',
  },
  { name: 'popover', path: '/example/command/popover' },
  { name: 'context-menu/demo', path: '/example/context-menu/demo' },
  { name: 'dialog/demo', path: '/example/dialog/demo' },
  {
    name: 'dropdown-menu/checkboxes',
    path: '/example/dropdown-menu/checkboxes',
  },
  {
    name: 'dropdown-menu/demo',
    path: '/example/dropdown-menu/demo',
  },
  {
    name: 'dropdown-menu/radio-group',
    path: '/example/dropdown-menu/radio-group',
  },
  { name: 'hover-card/demo', path: '/example/hover-card/demo' },
  { name: 'input/demo', path: '/example/input/demo' },
  { name: 'input/disabled', path: '/example/input/disabled' },
  { name: 'input/file', path: '/example/input/file' },
  { name: 'input/with-button', path: '/example/input/with-button' },
  { name: 'input/with-label', path: '/example/input/with-label' },
  { name: 'input/with-text', path: '/example/input/with-text' },
  { name: 'label/demo', path: '/example/label/demo' },
  { name: 'menubar/demo', path: '/example/menubar/demo' },
  {
    name: 'navigation-menu/demo',
    path: '/example/navigation-menu/demo',
  },
  { name: 'popover/demo', path: '/example/popover/demo' },
  { name: 'progress/demo', path: '/example/progress/demo' },
  { name: 'radio-group/demo', path: '/example/radio-group/demo' },
  { name: 'scroll-area/demo', path: '/example/scroll-area/demo' },
  { name: 'select/demo', path: '/example/select/demo' },
  { name: 'separator/demo', path: '/example/separator/demo' },
  { name: 'sheet/demo', path: '/example/sheet/demo' },
  { name: 'sheet/position', path: '/example/sheet/position' },
  { name: 'sheet/size', path: '/example/sheet/size' },
  { name: 'skeleton/demo', path: '/example/skeleton/demo' },
  { name: 'slider/demo', path: '/example/slider/demo' },
  { name: 'switch/demo', path: '/example/switch/demo' },
  { name: 'tabs/demo', path: '/example/tabs/demo' },
  { name: 'textarea/demo', path: '/example/textarea/demo' },
  { name: 'textarea/disabled', path: '/example/textarea/disabled' },
  {
    name: 'textarea/with-button',
    path: '/example/textarea/with-button',
  },
  {
    name: 'textarea/with-label',
    path: '/example/textarea/with-label',
  },
  {
    name: 'textarea/with-text',
    path: '/example/textarea/with-text',
  },
  { name: 'toast/demo', path: '/example/toast/demo' },
  { name: 'toast/destructive', path: '/example/toast/destructive' },
  { name: 'toast/simple', path: '/example/toast/simple' },
  { name: 'toast/with-action', path: '/example/toast/with-action' },
  { name: 'toast/with-title', path: '/example/toast/with-title' },
  { name: 'toggle/demo', path: '/example/toggle/demo' },
  { name: 'toggle/disabled', path: '/example/toggle/disabled' },
  { name: 'toggle/lg', path: '/example/toggle/lg' },
  { name: 'toggle/outline', path: '/example/toggle/outline' },
  { name: 'toggle/sm', path: '/example/toggle/sm' },
  { name: 'toggle/with-text', path: '/example/toggle/with-text' },
  { name: 'tooltip/demo', path: '/example/tooltip/demo' },
  {
    name: 'typography/blockquote',
    path: 'typography/blockquote',
  },
  { name: '/example/typography/demo', path: '/example/typography/demo' },
  { name: '/example/typography/h1', path: '/example/typography/h1' },
  { name: '/example/typography/h2', path: '/example/typography/h2' },
  { name: '/example/typography/h3', path: '/example/typography/h3' },
  { name: '/example/typography/h4', path: '/example/typography/h4' },
  {
    name: '/example/typography/inline-code',
    path: '/example/typography/inline-code',
  },
  { name: '/example/typography/large', path: '/example/typography/large' },
  { name: '/example/typography/lead', path: '/example/typography/lead' },
  { name: '/example/typography/list', path: '/example/typography/list' },
  { name: '/example/typography/muted', path: '/example/typography/muted' },
  { name: '/example/typography/p', path: '/example/typography/p' },
  { name: '/example/typography/small', path: '/example/typography/small' },
  { name: '/example/typography/table', path: '/example/typography/table' },
  { name: '/example/markdown/editor', path: '/example/markdown/editor' },
];
export const studyLists = [
  { name: 'Vue Life-Cycle', path: '/study/vue/life-cycle' },
];
